// <auto-generated />
using System;
using DteamBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DteamBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909155516_MbLastMigration")]
    partial class MbLastMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DteamBackend.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletedForReceiver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletedForSender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SenderId", "ClientMessageId")
                        .IsUnique();

                    b.HasIndex("ReceiverId", "SenderId", "CreatedAt");

                    b.HasIndex("ReceiverId", "Status", "CreatedAt");

                    b.HasIndex("SenderId", "ReceiverId", "CreatedAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DteamBackend.Models.ChatUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCommitted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUploads");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LikedByUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("CommunityComments");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameBannerUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameGuidId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LikedByUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameGuidId");

                    b.HasIndex("GameId");

                    b.ToTable("CommunityPosts");
                });

            modelBuilder.Entity("DteamBackend.Models.Duser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("BalanceInNanoTons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FamilyOwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardhatAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInFamily")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDisconnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TasteVectorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeRewardNftsMintedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalEarningsInNanoTons")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTimeSpentSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FamilyOwnerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WalletAddress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DteamBackend.Models.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "ReceiverId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("DteamBackend.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDlc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentGameId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceInNanoTons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ScreenshotUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerArchivePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportedLanguages")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TasteVectorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentGameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DteamBackend.Models.GameCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("GameCollections");
                });

            modelBuilder.Entity("DteamBackend.Models.GameCollectionItem", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameCollectionItems");
                });

            modelBuilder.Entity("DteamBackend.Models.NftItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMinted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTransferredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceInPoints")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TokenId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsMinted");

                    b.HasIndex("Rarity");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.HasIndex("BackgroundIndex", "PatternIndex", "ModelIndex")
                        .IsUnique();

                    b.ToTable("NftItems");
                });

            modelBuilder.Entity("DteamBackend.Models.NftTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NftItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromAddress");

                    b.HasIndex("FromUserId");

                    b.HasIndex("NftItemId");

                    b.HasIndex("ToAddress");

                    b.HasIndex("ToUserId");

                    b.HasIndex("TokenId");

                    b.HasIndex("TransferredAt");

                    b.ToTable("NftTransfers");
                });

            modelBuilder.Entity("DteamBackend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("UserId", "IsDeleted", "CreatedAt");

                    b.HasIndex("UserId", "IsDeleted", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DteamBackend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DteamBackend.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikedByUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentReviewId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PlayTimeHoursAtReview")
                        .HasColumnType("REAL");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique()
                        .HasFilter("\"ParentReviewId\" IS NULL");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DteamBackend.Models.Tranxaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TxhHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TxhHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tranxactions");
                });

            modelBuilder.Entity("DteamBackend.Models.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("DteamBackend.Models.UserBlock", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "BlockedUserId");

                    b.HasIndex("BlockedUserId");

                    b.ToTable("UserBlocks", (string)null);
                });

            modelBuilder.Entity("DteamBackend.Models.UserCartItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserCartItems");
                });

            modelBuilder.Entity("DteamBackend.Models.UserFriend", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("UserFriends", (string)null);
                });

            modelBuilder.Entity("DteamBackend.Models.UserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("DteamBackend.Models.UserNotificationPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChatNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChatSoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyBigSales")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyFriendRequestAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyFriendRequestDeclined")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyFriendRequests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyProfileComments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyWishlistDiscounts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserNotificationPreferences");
                });

            modelBuilder.Entity("DteamBackend.Models.UserWishlist", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserWishlists");
                });

            modelBuilder.Entity("DteamBackend.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountInNanoTons")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("DteamBackend.Models.ChatMessage", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DteamBackend.Models.ChatUpload", b =>
                {
                    b.HasOne("DteamBackend.Models.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityComment", b =>
                {
                    b.HasOne("DteamBackend.Models.CommunityComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DteamBackend.Models.CommunityPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DteamBackend.Models.AuthorDto", "Author", b1 =>
                        {
                            b1.Property<string>("CommunityCommentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AvatarUrl")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorAvatarUrl");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorId");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorUsername");

                            b1.HasKey("CommunityCommentId");

                            b1.ToTable("CommunityComments");

                            b1.WithOwner()
                                .HasForeignKey("CommunityCommentId");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityPost", b =>
                {
                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("GameGuidId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("DteamBackend.Models.AuthorDto", "Author", b1 =>
                        {
                            b1.Property<string>("CommunityPostId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AvatarUrl")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorAvatarUrl");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorId");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorUsername");

                            b1.HasKey("CommunityPostId");

                            b1.ToTable("CommunityPosts");

                            b1.WithOwner()
                                .HasForeignKey("CommunityPostId");
                        });

                    b.OwnsOne("DteamBackend.Models.PostMedia", "Media", b1 =>
                        {
                            b1.Property<string>("CommunityPostId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ThumbnailUrl")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MediaThumbnailUrl");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MediaType");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("MediaUrl");

                            b1.HasKey("CommunityPostId");

                            b1.ToTable("CommunityPosts");

                            b1.WithOwner()
                                .HasForeignKey("CommunityPostId");
                        });

                    b.Navigation("Author")
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Media")
                        .IsRequired();
                });

            modelBuilder.Entity("DteamBackend.Models.Duser", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "FamilyOwner")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FamilyOwner");
                });

            modelBuilder.Entity("DteamBackend.Models.FriendRequest", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DteamBackend.Models.Game", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "Owner")
                        .WithMany("CreatedGames")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Game", "ParentGame")
                        .WithMany("Dlcs")
                        .HasForeignKey("ParentGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("ParentGame");
                });

            modelBuilder.Entity("DteamBackend.Models.GameCollection", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.GameCollectionItem", b =>
                {
                    b.HasOne("DteamBackend.Models.GameCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DteamBackend.Models.NftItem", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Gifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.NftTransfer", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DteamBackend.Models.NftItem", "NftItem")
                        .WithMany()
                        .HasForeignKey("NftItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FromUser");

                    b.Navigation("NftItem");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("DteamBackend.Models.Notification", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.Review", b =>
                {
                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Review", "ParentReview")
                        .WithMany("Replies")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("ParentReview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.Tranxaction", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserActivity", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserBlock", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserCartItem", b =>
                {
                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany("InCartsOf")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserFriend", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Friendships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserGame", b =>
                {
                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany("Owners")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Library")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserNotificationPreferences", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithOne("NotificationPreferences")
                        .HasForeignKey("DteamBackend.Models.UserNotificationPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.UserWishlist", b =>
                {
                    b.HasOne("DteamBackend.Models.Game", "Game")
                        .WithMany("WishlistedBy")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.WalletTransaction", b =>
                {
                    b.HasOne("DteamBackend.Models.Duser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("DteamBackend.Models.CommunityPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DteamBackend.Models.Duser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CartItems");

                    b.Navigation("Collections");

                    b.Navigation("CreatedGames");

                    b.Navigation("FamilyMembers");

                    b.Navigation("Friendships");

                    b.Navigation("Gifts");

                    b.Navigation("Library");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("Reviews");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("DteamBackend.Models.Game", b =>
                {
                    b.Navigation("CommunityPosts");

                    b.Navigation("Dlcs");

                    b.Navigation("InCartsOf");

                    b.Navigation("Owners");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistedBy");
                });

            modelBuilder.Entity("DteamBackend.Models.GameCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DteamBackend.Models.Review", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
